---
title: "Exploratory Data Analysis"
author: "Cameron Hansen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Fix this Chart?

## Orginal  Graph

```{r}
library(readr) # loading in readr package
library(ggplot2) # loading in ggplot2 package


rcw <- read_csv("https://byuistats.github.io/M335/data/rcw.csv", 
                col_types = cols(Semester_Date = col_date(format = "%m/%d/%y"), 
                                 Semester = col_factor(levels = c("Winter", "Spring", "Fall")))) #takes the data from the github repository and stories it in a vector rwc. 
#Then formates the semester date to a date data type then in month day year order.
# Then takes semester column and turns it into a factor with Winter Spring and Fall as the accepted types 

# displays the first five rows of the vector
head(rcw)

# Maps the rcw data to the x and y and then groups the data by department shown by color
ggplot(data = rcw, 
       mapping = aes(x = Semester_Date, 
                     y = Count, 
                     color = Department)) +
  geom_line()  + #Creates a line graph
  geom_point() # Creates a point for every observation for each group


```

## My improvements

```{r}
library(tidyverse)



ggplot(data = rcw) +
  geom_smooth(aes(x = Semester_Date,
                  y = Count))

ggplot(data = rcw) +
  geom_bar(mapping = aes(x = Semester,
                         y = Count,
                         fill = Department)
           ,stat="identity")
  
```

